### ISSUE TITLE
How do I make this work consistently?

### ISSUE THREAD

**Issue by KTsarlz** [alienator88/slacky-dark#1]
On first try I was able to make this work on windows client V3.2.0, but after reloading Slack, it reverted to white.

Tried multiple times. reloading, quitting the app and all but I can't get the dark mode work. 

Any tips as to how I can make this work consistently?

**Comment by alienator88** [comment]
I had this happen once for me a couple weeks back. In my case it went back to normal after quitting the app and starting it again. Try uninstalling the app and then delete everything under: %homepath%\AppData\Local\slack\ to make sure all the slack cache is gone too. Then reinstall again and add the code to the ssb-interop.js file again.
Something else that could cause it is if the URL to the github is somehow not allowed access and the ssb-interop file can't load the CSS data. I have multiple people using this currently at my work without issue, so I'm thinking it might be a config problem on your end with the computer/network maybe.

**Comment by KTsarlz** [comment]
I just reinstalled before creating an issue... Still the same. It was working before 3.2.0 update tho. Will try again

**Comment by alienator88** [comment]
Try adding the piece of code to this file as well:
`%homepath%\AppData\Local\slack\app-3.2.0\resources\app.asar.unpacked\src\static\index.js`

**Comment by KTsarlz** [comment]
dang still no luck, i just changed to darkside and now I can't make it work with the original dark css

**Comment by alienator88** [comment]
Ah dang, sorry man. I'm not sure how I could help without being able to reproduce it unfortunately. I've asked around at my work and nobody else is seeing an issue at the moment, theme loads fine. 
Have you tried maybe installing a version below 3.2.0 just to see if it's the new version causing it?
https://www.filecluster.com/downloads/Slack.html

**Comment by KTsarlz** [comment]
This sucks :(( I really wanted to use your css as it has white font. I have tried others before using the same snippet but different CSS. But as of now, nothing works..

**Comment by alienator88** [comment]
If I were you, I would try testing on another computer and also on another network to rule out computer/firewall issues. If it's failing to load the CSS in the javascript file, it means something is blocking the URL from pulling the raw code.

**Comment by KTsarlz** [comment]
I did try that. I'm on the same machine and network for quite some time. And it just now, it doesn't work. Before I've been using Lacour's code, it was working well. I just tried to change the css now since I find yours appealing to eyes. And it did work immediately, but I tried darkside to have the red look.. After that nothing worked anymore haha

**Comment by alienator88** [comment]
That's super strange. 
Question, when you uninstalled, did you try removing the slack folder from both of these locations?
%homepath%\AppData\Local\slack
%homepath%\AppData\Roaming\slack

The app puts files in both of those. After uninstall and fully removing the slack folders in both of those areas, try running disk cleanup (cleanmgr.exe) on the drive and erase everything in there.

**Comment by KTsarlz** [comment]
Oh. I only shift deleted files in local, will try in roaming too.

Also my machine was just reimaged.. So after installing it shouldn't have cache. 

Is the file in roaming needs also changing?

**Comment by alienator88** [comment]
No, you shouldn't need to change anything in Roaming.

**Comment by KTsarlz** [comment]
Will try, shift deleting those folders.. Hope this will work!

**Comment by KTsarlz** [comment]
And now it worked! With the dark css

**Comment by alienator88** [comment]
Nice, stupid caching. Glad it worked out for ya. Go ahead and close the issue when ready :)
