### ISSUE TITLE
Green text for unread convos

### ISSUE THREAD

**Issue by RheingoldRiver** [alienator88/slacky-dark#10]
In my fork of this I changed the colors of unread convos to be green text instead of normal white text, because that makes it a lot easier to read, the rules are:

.p-channel_sidebar__channel--unread:not(.p-channel_sidebar__channel--muted)::before {
  color:#61AF28!important;
}

.p-channel_sidebar__channel--unread:not(.p-channel_sidebar__channel--muted) span {
  color:#61AF28!important;
  font-weight:bold!important;
}

Would you be ok with adding that to yours? I also have fixes for a couple other things (thread replies in particular), so I can make a pull request with everything if you want.

**Comment by alienator88** [comment]
Hey, 

That's a good idea actually, others might like that. But on this one in particular, I use it personally and my taste is really minimalistic and least amount of color. Lots of gray and black for me haha.
