### ISSUE TITLE
[Win10] "slack" folder does not exist

### ISSUE THREAD

**Issue by KaKi87** [alienator88/slacky-dark#3]
Hello,

I firstly tried the manual tutorial but there is no `AppData\Local\slack\` folder on my computer, then I tried the script and there's the same problem.

```
Get-ChildItem : Cannot find path 'C:\Users\<user>\AppData\Local\slack\' because it does not
exist.
```

Thanks

**Comment by alienator88** [comment]
Hi, did you install the Slack app from the Windows Store by chance? That one doesn't get installed the same way. You'd need to download the desktop version from the slack website.

**Comment by KaKi87** [comment]
Yes it works, thanks !
PS : could you add that in the README ?

**Comment by alienator88** [comment]
Awesome. I'll add it to the readme.
