### ISSUE TITLE
Cannot make it do the task 

### ISSUE THREAD

**Issue by MarcSteven** [alienator88/slacky-dark#4]
When edit is finished ,and then clicked the save ,it displayed error "ESC12"

**Comment by alienator88** [comment]
I've never seen or heard of that error before.
Could you attach a screenshot?
Also, this happens right after adding the javascript to the ssb-interop.js file and trying to save?

**Comment by MarcSteven** [comment]
@alienator88  Yeah I add the code at the bottom of file (I copied the code) And then save ,it showed me error

**Comment by alienator88** [comment]
I see. Can you reproduce it again, take a screenshot and just drag the picture here in the message box?
It should attach it.

**Comment by MarcSteven** [comment]
<img width="797" alt="2018-10-02 12 09 49" src="https://user-images.githubusercontent.com/13824297/46300952-8d0ed480-c5d7-11e8-86a5-1d6ec4d4a05e.png">
Perhaps it's because the file is readonly file ,so writing is impossible to accomplish.

**Comment by alienator88** [comment]
I don't remember having this issue on my Mac. Do you get the same error if you use "sudo vim" instead?
Or right click the file > Get Info and give yourself read/write permissions?
Also make sure the Slack app is not running while editing this too.

**Comment by MarcSteven** [comment]
Perhaps the file just own read permissions ,I closed my slack and then all is wrong, deep nite ,so I must go to bed ,I will try tomorrow morning and then hope it goes well!Thank for your tips!!

**Comment by alienator88** [comment]
No problem. Let me know if you need more help later.
