### ISSUE TITLE
Thread side window coloring issues

### ISSUE THREAD

**Issue by santoshiyer** [alienator88/slacky-dark#8]
Hi,

I noticed that thread header and reply boxes are mismatched in coloring (white).  Please see the attached image
![capture](https://user-images.githubusercontent.com/6622399/51806408-95a2af00-2247-11e9-8279-00a0556c4106.PNG)

Any ideas on how to change these?

**Comment by RheingoldRiver** [comment]
I fixed this in my fork but it's a lot of versions behind in some other regards. The rules I have are:

.p-threads_footer__input {
    background-color: #222!important;
}

.c-button-unstyled {
    background-color: #222!important;
}

.ql-editor {
    background-color:#222!important;
}

.p-threads_flexpane__header {
 background-color:#222!important; 
}

.p-threads_footer__input .p-message_input_field {
 background-color:#222!important; 
}


but some of them are probably redundant

**Comment by alienator88** [comment]
Hey guys, sorry it's taken me a while to get back. I've been cramming for exams.
So I just checked my slack app on my windows and mac computers and none of them have the white thread header and reply box. I've seen this happen before with another user where caching from multiple slack updates kind of broke it. This is what I had him do to fix it:

Uninstall the app, delete the slack folder under %homepath%\AppData\Local\ and %homepath%\AppData\Roaming.
Then reinstall app again.

Let me know if that resolves it.

**Comment by alienator88** [comment]
![screen shot 2019-02-05 at 7 21 14 pm](https://user-images.githubusercontent.com/6263626/52316978-3ba69580-297b-11e9-9012-9e19d8da68bf.png)

**Comment by alienator88** [comment]
Really strange, I'll add his css rules just in case anybody else experiences this.
Thanks for the update.
